---
- name: Install and configure etcd on RHEL
  hosts: all
  become: true

  vars:
    etcd_version: "v3.5.16"
    etcd_download_url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    etcd_bin_path: "/usr/local/bin"
    etcd_data_dir: "/var/lib/etcd"
    etcd_service_path: "/etc/systemd/system/etcd.service"

  tasks:
    - name: Create etcd user and group
      user:
        name: etcd
        shell: /sbin/nologin
        create_home: no
        state: present

    - name: Download etcd binary
      get_url:
        url: "{{ etcd_download_url }}"
        dest: /tmp/etcd.tar.gz
        mode: "0644"

    - name: Extract etcd binary
      unarchive:
        src: /tmp/etcd.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move binaries to /usr/local/bin
      copy:
        remote_src: yes
        src: "/tmp/etcd-{{ etcd_version }}-linux-amd64/etcd"
        dest: "{{ etcd_bin_path }}/etcd"
        mode: "0755"

    - name: Move etcdctl binary to /usr/local/bin
      copy:
        remote_src: yes
        src: "/tmp/etcd-{{ etcd_version }}-linux-amd64/etcdctl"
        dest: "{{ etcd_bin_path }}/etcdctl"
        mode: "0755"

    - name: Ensure etcd data directory exists
      file:
        path: "{{ etcd_data_dir }}"
        state: directory
        owner: etcd
        group: etcd
        mode: "0755"

    - name: Create systemd service file for etcd
      copy:
        dest: "{{ etcd_service_path }}"
        content: |
          [Unit]
          Description=etcd key-value store
          Documentation=https://github.com/etcd-io/etcd
          After=network-online.target local-fs.target remote-fs.target time-sync.target
          Wants=network-online.target local-fs.target remote-fs.target time-sync.target

          [Service]
          User=etcd
          Type=notify

          Environment=ETCD_DATA_DIR={{ etcd_data_dir }}
          Environment=ETCD_NAME={{ inventory_hostname }}
          Environment=ETCD_INITIAL_ADVERTISE_PEER_URLS=http://{{ hostvars[inventory_hostname].private_ip }}:2380
          Environment=ETCD_LISTEN_PEER_URLS=http://{{ hostvars[inventory_hostname].private_ip }}:2380
          Environment=ETCD_LISTEN_CLIENT_URLS=http://{{ hostvars[inventory_hostname].private_ip }}:2379,http://127.0.0.1:2379
          Environment=ETCD_ADVERTISE_CLIENT_URLS=http://{{ hostvars[inventory_hostname].private_ip }}:2379
          Environment=ETCD_INITIAL_CLUSTER_TOKEN=phctoken
          Environment=ETCD_INITIAL_CLUSTER=node1=http://10.10.120.11:2380,node2=http://10.10.120.12:2380,node3=http://10.10.120.13:2380
          Environment=ETCD_INITIAL_CLUSTER_STATE=new

          ExecStart={{ etcd_bin_path }}/etcd
          Restart=always
          RestartSec=10s
          LimitNOFILE=40000

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: "0644"

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable etcd service
      systemd:
        name: etcd
        enabled: true

    - name: Clean up temporary files
      file:
        path: /tmp/etcd.tar.gz
        state: absent

    - name: Clean up temporary extracted files
      file:
        path: "/tmp/etcd-{{ etcd_version }}-linux-amd64"
        state: absent

    - name: Open etcd ports in firewalld
      firewalld:
        port: "{{ item }}"
        zone: public
        permanent: true
        state: enabled
      loop:
        - 2379/tcp
        - 2380/tcp

    - name: Reload firewalld to apply changes
      command: firewall-cmd --reload

    - name: Start etcd service
      systemd:
        name: etcd
        state: started
